{{- if eq .Values.global.platform "OPENSHIFT" }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  generation: 1
  name: {{ .Values.apimgr.image }}
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: {{ .Values.global.dockerRepository }}/{{ .Values.apimgr.image }}:{{ $imageTag }}
    name: latest
    importPolicy:
      insecure: true 
    referencePolicy:
      type: Local
  lookupPolicy:
    local: true 
{{- end }}