{{- if eq .Values.global.platform "OPENSHIFT" }}
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-build-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  config.props: |-
              {{ .Files.Get "Secrets/config.props" | b64enc }}
  lic.lic: |-
            {{ .Files.Get (printf "Secrets/%s" .Values.global.license) | b64enc }}
  domaincert.pem: |-
                  {{ .Files.Get (printf "Secrets/%s" .Values.global.domainCert) | b64enc }}
  domainkey.pem: |-
                  {{ .Files.Get (printf "Secrets/%s" .Values.global.domainKey) | b64enc }}
{{- end }}